[package]
name = "dpc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
dashmap = "5.5.3"
itertools = "0.11.0"
rand = "0.8.5"
rayon = "1.8.0"
serde = "1.0.188"
serde_json = "1.0.107"
tinyvec = { version = "1.6.0", features = ["alloc"] }
